### ISSUE TITLE
codon throws error when comparing `union` value with `int` value

### ISSUE THREAD

**Issue by learnforpractice** [exaloop/codon#156]
t3.py

```python
a: Union[int, str] = 123
print(123 == a)
print(a == 123)
```

```
codon run t3.py
```

output:

```
internal.codon:125:13-75: error: 'str' object has no method '__eq__' with arguments (str, int)
├─ internal.codon:125:13-75: error: during the realization of _get_union_method(union: Union[int,str], method: '__eq__', *args: Tuple[int], **kwargs: KwTuple.N0)
╰─ t3.py:3:7-15: error: during the realization of get_union_method(union: Union[int,str], method: '__eq__', *args: Tuple[int], **kwargs: KwTuple.N0)
```

**Comment by inumanag** [comment]
Hi @learnforpractice 

This behaviour is expected and is made default by design. 

All members of the Union must support `__eq__(self, int)` (or any other call, for that matter). In this case, strings cannot be compared with ints, so this fails. If this is not the case, you could do later `a = "123"` and try `a == 123`; this would result in runtime error in Python, but in Codon it is a compile error.

**Comment by learnforpractice** [comment]
Thanks for the explanation. The implementation of the Union type can be challenging.
I think here is the code for generating the `__eq__` method for Union type:
https://github.com/exaloop/codon/blob/8421e8fb03fe10a6f91d23c433f036e6ceb20a7a/codon/parser/visitors/typecheck/infer.cpp#L899

**Comment by inumanag** [comment]
Correct, that method basically check the union tag and calls the corresponding type's  `__eq__(self, int)` in this case. As `str` does not have such `__eq__`, it raises an error.

**Comment by inumanag** [comment]
OK, we added support for this. You will get an exception instead of compile error this time. Will probably add a warning in the future versions to warn that this can result in runtime error.
