### ISSUE TITLE
Please provide evidence for performance claims

### ISSUE THREAD

**Issue by markshannon** [exaloop/codon#160]
The readme claims "Typical speedups over Python are on the order of 10-100x or more, on a single thread."

Where do these numbers come from?

Please provide the benchmarks used, and any additional information needed to reproduce the result.

**Comment by arshajii** [comment]
Hi @markshannon — see https://exaloop.io/benchmarks.html for performance results and exact setups used. All the code is in `bench/` along with detailed descriptions if you wanted to try it yourself. A couple of these use multi-threading; you can disable that by commenting the `@par` line to see single-threaded performance. We also have broader benchmarks in some of our older papers, e.g. [here](https://dl.acm.org/doi/10.1145/3360551).

**Comment by markshannon** [comment]
It seems unreasonable to claim "typical speedups" from such a small set of benchmarks.
Why not use the standard benchmark suite?

Which version of Python are you comparing against?
What is your methodology? Do the Codon times include the full clock time, or are you discarding compilation time?

**Comment by arshajii** [comment]
Many of the benchmarks from the pyperformance suite use various libraries that aren't supported by Codon; we've included the ones that Codon can (as of today) compile with minimal or no changes. If you have other benchmarks in mind we'd be happy to take a look and incorporate them.

The Python versions are given in the benchmark link I shared (3.10.8 and 3.8.2). I know 3.11 includes performance improvements -- we'll be using it when we run the benchmarks next.

You can look at the [`bench.sh`](https://github.com/exaloop/codon/blob/develop/bench/bench.sh) script to see how the benchmarks are run. Compile times for Codon (and C++) are not included in the reported runtimes, since Codon is an ahead-of-time compiler in general.

Lastly I'll mention that the speedup over Python can be arbitrarily high depending on the program. For example there is also a `bench/sum` benchmark where Codon is something like 10<sup>7</sup> times faster because it optimizes the entire loop away and just precomputes the answer. We didn't include this one in the results as it can be misleading in this regard.

**Comment by markshannon** [comment]
"Codon is a high-performance Python compiler..." rather implies that Codon supports Python. 
If it that isn't true, why claim to be a Python compiler?

Perhaps make it clearer that Codon isn't Python, but a statically compiled subset that shares syntax; like [RPython](https://rpython.readthedocs.io/en/latest/)?

**Comment by arshajii** [comment]
To be honest I think we *are* pretty upfront and clear about that: we say it in the README ([*What isn't Codon?*](https://github.com/exaloop/codon#what-isnt-codon)) and in the docs ([*FAQ*](https://docs.exaloop.io/codon/general/faq) and [*Differences with Python*](https://docs.exaloop.io/codon/general/differences)). I don't think calling something a "Python compiler" implies it can handle 100% of Python; for example Numba is described as a "NumPy aware dynamic Python compiler using LLVM" on GitHub, and Codon can handle a lot more of Python than Numba.

**Comment by learnforpractice** [comment]
The performance of codon is truly impressive. However, for the long-term success of the project, I think it would be more beneficial to focus on ensuring compatibility and stability in addition to performance.

**Comment by markshannon** [comment]
From top of the numba home page:
"Numba is an open source JIT compiler that translates a **subset** of Python and NumPy code into fast machine code." (Emphasis mine)

Contrast that with Nuitka, which claims to be a "Python compiler with full language support and CPython compatibility"

> Codon can handle a lot more of Python than Numba.

Can it? Again, where is your evidence?
Sure, Numba has its limitations, but Codon doesn't support strings or long integers.

**Comment by arshajii** [comment]
> The performance of codon is truly impressive. However, for the long-term success of the project, I think it would be more beneficial to focus on ensuring compatibility and stability in addition to performance.

Definitely -- that's the direction we want to push towards. Still a lot more we can do to close the gap and make it more compatible :)

**Comment by arshajii** [comment]
@markshannon The Numba GitHub has the description I shared with the first sentence in the README being *"Numba is an open source, NumPy-aware optimizing compiler for Python"*. It makes sense that they also characterize its limitations ("subset" etc.); so does the Codon README.

I guess I'm not really sure what it is you're asking for here?

**Comment by markshannon** [comment]
I'm asking that you make claims backed up by evidence, and link to that evidence.

You claim that Codon is a general-purpose Python compiler, but it can only handle a few very simple programs.
You claim that Codon is 10 to 100x faster than Python, but your evidence is a very small number of hand picked examples.

**Comment by learnforpractice** [comment]
> I'm asking that you make claims backed up by evidence, and link to that evidence.
> 
> You claim that Codon is a general-purpose Python compiler, but it can only handle a few very simple programs. You claim that Codon is 10 to 100x faster than Python, but your evidence is a very small number of hand picked examples.

Codon is not fully compatible with CPython.  It is an acceptable trade-off as we require a pythonic static compiler that prioritizes both good performance and compatibility

**Comment by arshajii** [comment]
@markshannon There’s not a whole lot more I can offer you here unfortunately. The relative performance of two languages/implementations varies greatly based on the program; sometimes Python and Codon will be about the same speed, sometimes Codon will be orders of magnitude faster, like in the example I gave above. We’ve found through these benchmarks and in general that Codon is typically 10-100x faster on most programs (which as expected is roughly on par with Python vs. C++; e.g. https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/python3-gpp.html). Like I said, we’re more than happy to incorporate other benchmarks (and plan to as we increase our compatibility). I’m not sure what you mean by “hand picked”—we did exactly what I said in my previous comment: took the benchmarks that Codon can compile with minimal/no changes, and certainly did not exclude any where Codon was not as fast, if that’s what you mean.

I think I answered the “Python compiler” question previously; being a “Python compiler” doesn’t imply 100% compatibility, which is why e.g. Numba is usually referred to, and advertises itself as, a “Python compiler”, even though its not a drop-in replacement for CPython.

**Comment by learnforpractice** [comment]
Yes, I think it is fine to refer to Codon as a "Python compiler" despite its lack of full compatibility with CPython.

**Comment by inumanag** [comment]
PL benchmarks are always a whack-a-mole game: you can always come up with individual cases that either prove or disprove the main point. Our benchmarks were chosen by taking commonly used benchmarks and adapting them for Codon. If you think we missed anything, please let us know and we will gladly add them. The speed-up claims are also backed up by quite a lot of real-world applications we used with Codon: lots of examples are available in https://www.nature.com/articles/s41587-021-00985-6 (see Supplementaries for details).

As for compatibility: while Codon currently covers lots of Python, there are still gaps that need to be filled in. This is work in progress, mind you— Python itself is 30+ year old and it takes some time to catch up, especially considering the attack strategy we chose. 

Closing this issue as nothing else can be said. Feel free to submit benchmark PRs, especially if they disprove our claims: we are indeed looking for cases where Codon under-performs as compared to Python or pypy :)

**Comment by markshannon** [comment]
> Feel free to submit benchmark PRs

Use the standard benchmark suite. It is freely available (unlike the article you linked to).
