### ISSUE TITLE
PyError: module 'sys' has no attribute 'argv'

### ISSUE THREAD

**Issue by coldcodefire** [exaloop/codon#184]
when performing "codon run mycode.py" which is an application based on flask, and flask depends on werkzeug module, in werkzeug, "sys.argv[0]" was read to determine how the scripts was performed.  but unforunately, seems sys module in codon has no argc and argv like normal python env. appreciate for any help. 

Thanks

**Comment by inumanag** [comment]
@coldcodefire 

Codon does not (yet) export `sys.argv` with Python bridge.

Also, if you are using Flask---which uses lots of features we don't yet support---I'd suggest using `@codon` decorator to speed-up the specific bottlenecks instead of running the whole thing via Codon. Just running stuff with Codon won't bring the speed-ups if the library of interest is invoked via Python bridge.

**Comment by inumanag** [comment]
Merging into #608 .
