### ISSUE TITLE
get minus mod value

### ISSUE THREAD

**Issue by Erimus-Koo** [exaloop/codon#186]
## fib.py

```python

import time
start = time.time()


def fib(n):
    a, b = 0, 1
    for _ in range(n):
        a, b = b, a + b
    print(f'%a = {a%123456789}')


fib(10**6)

print(f'Spend: {time.time()-start}')
```

## Result
```
> codon run fib.py
%a = -115020534
Spend: 0.00212407

> python3.11 fib.py
%a = 88373247
Spend: 11.893308877944946
```

It's really fast, but why?

**Comment by arshajii** [comment]
Hi @Erimus-Koo, this is because of an overflow in the `a` variable in Codon. Codon's `int` is 64-bit, unlike Python 3's arbitrary-width int type, so it ends up becoming a negative value. (If you print `a`, you will see `-4249520595888827205`.)

Unrelated point, but you can use the `-release` flag to enable optimizations; in this case it makes the code ~10x faster.

**Comment by Erimus-Koo** [comment]
@arshajii Thanks for your reply and I got it, I'll have a try about the `-release`.
And is there a doc of all similar situations.

**Comment by arshajii** [comment]
Yes, please see https://docs.exaloop.io/codon/general/differences.
