### ISSUE TITLE
Why `math.factorial(21)` is not supported? 

### ISSUE THREAD

**Issue by ARYASINGHBJC** [exaloop/codon#256]
Can we add support for `math.factorial(>20)`

**Comment by arshajii** [comment]
This is because Codon's `int`s are 64-bit (see https://docs.exaloop.io/codon/general/differences#data-types), so "20!" is the largest output that can be represented. Codon does support larger bit-width integers though if that fits your use case: https://docs.exaloop.io/codon/language/extra#arbitrary-width-integers.

**Comment by ARYASINGHBJC** [comment]
Thanks for clarification
