### ISSUE TITLE
Lists with members of different types or unknown types cannot be initialized

### ISSUE THREAD

**Issue by sss-patrick** [exaloop/codon#290]
This does not work:
codon run <(echo "test_vec = [ '1', '2', 3 ]")
63:1:12-27: error: 'List[str]' object has no method 'append' with arguments (List[str], int)

Nor does this:
codon run <(echo "test_vec = [ [], [], [] ]")
error: cannot typecheck the program

Nor even this:
codon run <(echo "test_vec = []")
error: cannot typecheck the program

Am I wrong in expecting that these should work?
This is certainly a show stopper for me in my attempt to use codon.

**Comment by elisbyberi** [comment]
Because Codon is strongly typed, these won't compile:

1. `codon run <(echo "test_vec = [ '1', '2', 3 ]")` will not work. From docs: `l = [1, 's']   # is it a List[int] or List[str]? you cannot mix-and-match types`

2. `codon run <(echo "test_vec = [ [], [], [] ]")` and `codon run <(echo "test_vec = []")` will not compile because all types must be known at compile time.

**Comment by arshajii** [comment]
Hi @sss-patrick -- it's possible to get this to work but currently you have to be explicit about the types:

``` python
test_vec = List[List[str]]()
test_vec.append([])
```

and

``` python
test_vec = List[Union[str,int]]()
test_vec.append('1')
test_vec.append('2')
test_vec.append(3)
```

**Comment by inumanag** [comment]
Yes, please see `https://docs.exaloop.io/codon/general/differences`.

Another way: `test_vec: List[List[str]] = [[], [], []]`.
