### ISSUE TITLE
import ``module`` follow relative path, and not root path

### ISSUE THREAD

**Issue by Rugau** [exaloop/codon#339]
0. Download this file
1. Run ``codon run q.py``
2. `b.py:1:8-9: error: no module named 'c'`

[folders_bug.zip](https://github.com/exaloop/codon/files/11181993/folders_bug.zip)

**Comment by elisbyberi** [comment]
@Rugau This is not a bug in Codon. Importing module c from module a.b is not supported in Python either. 

Please create a minimum reproducible example (MRE) in Python first and test it. The 'folders_bug.zip' file is not an MRE. Just because Python doesn't throw any exceptions doesn't necessarily mean that the code works correctly. If you declare some variables in module a, b, and c, try to use them from q.py, and encounter any errors or issues, please let me know.
