### ISSUE TITLE
Add native PyTorch support

### ISSUE THREAD

**Issue by janekb04** [exaloop/codon#349]
Similar to #224, which is about numpy.

Codon seems very promising in its ability to accelerate computationally-heavy Python applications. However, its adoption currently faces an important issue - the lack of native support for important Python computational frameworks and libraries.

_Maybe it would be useful to have one issue that would aggregate the most important libraries to port?_

**Comment by elisbyberi** [comment]
@janekb04 In my opinion, that may not be the most appropriate approach. Porting all the necessary libraries to make PyTorch Codon native would be a never-ending process since there are so many libraries involved:

1. astunparse
2. expecttest
3. hypothesis
4. numpy
5. psutil
6. pyyaml
7. requests
8. setuptools
9. types-dataclasses
10. typing-extensions
11. sympy
12. filelock
13. networkx
14. jinja2
15. fsspec

Also, Codon performance is on par with Numpy performance. Perhaps the best approach is to port the program from NumPy to Codon. The same goes for PyTorch.

**Comment by inumanag** [comment]
Please see https://docs.exaloop.io/codon/general/roadmap for details. Definitely planned for the future.

**Comment by inumanag** [comment]
Merging into #608 .
