### ISSUE TITLE
some questions I have

### ISSUE THREAD

**Issue by ckp95** [exaloop/codon#414]
Hi, found this from reading old hackernews articles about compiling python. I read through the readme and FAQ and I still have some things I'm confused about and those things didn't answer:

- how does this work exactly? i.e. how is your approach different from other projects that try to AOT compile python, like nuitka
- in the examples, how is it figuring out the types without type hinting? well I guess it must obviously be doing type inference, but that must run into limitations at some point because of python's dynamic nature. what's the boundary where shit breaks (if that makes sense)?
- how should I write my code to best take advantage of whatever codon is doing? what kind of programming constructs will be slow, what kind of things will be fast, how do I refactor to get more perf. will type hinting everything help, or not?
- does codon radically improve on python's startup time? that's the main reason I'm interested in a compiled python.

**Comment by inumanag** [comment]
Most of these questions are answered here: https://dl.acm.org/doi/10.1145/3578360.3580275
If you cannot access the PDF, please let me know and I will attach it here.

>  how should I write my code to best take advantage of whatever codon is doing? what kind of programming constructs will be slow, what kind of things will be fast, how do I refactor to get more perf. will type hinting everything help, or not?

If it compiles, it should work and should be fast. If the code does not compile, that means that Codon cannot handle it, most likely due to type issue or due to lacking some Python feature(s). The only exception to this rule are `from python` objects that are by definition linked to CPython and thus are as fast/slow as in Python.

> does codon radically improve on python's startup time? that's the main reason I'm interested in a compiled python.

Codon has virtually no start-up time (the only init we do is GC init and occasionally OpenMP init for parallel blocks, both which are instantaneous).
