### ISSUE TITLE
Can I use codon with Cffi?

### ISSUE THREAD

**Issue by nile649** [exaloop/codon#86]
I didn't find any discussion group.

**Comment by arshajii** [comment]
You can call C functions with `from C import` in Codon ([docs](https://docs.exaloop.io/codon/language/ffi)). See also ["Other types and features"](https://docs.exaloop.io/codon/language/extra) for how to express some C types in Codon. Generally calling C functions is very seamless/efficient (e.g. no object conversions are needed) since it's all LLVM-based anyway.

**Comment by inumanag** [comment]
I am closing this issue for now. 

You can (if you really want) use cffi via `from python import ctypes`, although this is highly discouraged---please use  Codon's native `from C import` if possible.
